@OrderFlow.API_HostAddress = https://localhost:7092

GET {{OrderFlow.API_HostAddress}}/weatherforecast/
Accept: application/json

###
@custname=DbDown
@custemail={{custname}}1515@gmail.com

POST {{OrderFlow.API_HostAddress}}/api/orders?custname={{custname}}&custemail={{custemail}}

###
